repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 0.5.3
    namespace: external-secrets
    createNamespace: true
    wait: true
    hooks:
      - events: ["cleanup"]
        showlogs: true
        command: "kubectl"
        args: ["wait", "--for", "condition=established", "--timeout=60s", "crd/externalsecrets.external-secrets.io"]
  - name: secrets
    chart: ./secrets/externalsecrets/
    namespace: external-secrets
    needs: ['external-secrets']
    values:
      - namespace: external-secrets
        provider: vault
        #aws:
        #  aws_region: us-east-1
        #  aws_access_key: {{ requiredEnv "AWS_ACCESS_KEY" }}
        #  aws_secret_key: {{ requiredEnv "AWS_SECRET_KEY" }}
        vault:
          server: "http://vault.vault.svc:8200"
          role: external-secrets
          grafana_path: kv/grafana/config
          mysql_path: kv/mysql/config
    wait: true
  - name: mysql
    chart: bitnami/mysql
    version: 9.0.4
    namespace: db
    createNamespace: true
    needs: ['external-secrets', 'secrets']
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["wait", "--for", "condition=Ready", "-n", "db", "--timeout=60s", "ExternalSecret/mysql-secret"]
    values:
      - auth:
          username: "app_user"
          existingSecret: mysql-secret
          database: grafana
        primary:
          persistence:
            enabled: false
  - name: grafana
    chart: grafana/grafana
    version: 6.29.4
    namespace: monitoring
    createNamespace: true
    needs: ['external-secrets', 'secrets']
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["wait", "--for", "condition=Ready", "-n", "monitoring", "--timeout=60s", "ExternalSecret/grafana-secret"]
    values:
      - admin:
          existingSecret: "grafana-secret"
          userKey: "admin_username"
          passwordKey: "admin_password"
        grafana.ini:
          database:
            type: mysql
            host: mysql.db
            name: grafana
        envValueFrom:
          GF_DATABASE_USER:
            secretKeyRef:
              name: grafana-secret
              key: db_username
          GF_DATABASE_PASSWORD:
            secretKeyRef:
              name: grafana-secret
              key: db_password
