apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  aws-access-key: {{ .Values.aws_access_key | b64enc }}
  aws-secret-key: {{ .Values.aws_secret_key | b64enc }}
