apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    {{- if eq .Values.provider "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.aws.aws_region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: aws-access-key
            namespace: {{ .Values.namespace }}
          secretAccessKeySecretRef:
            name: aws-secret
            key: aws-secret-key
            namespace: {{ .Values.namespace }}
    {{- else if eq .Values.provider "vault" }}
    vault:
      server: {{ .Values.vault.server }}
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role }}
    {{- end }}